'use strict';
const $=id=>document.getElementById(id), plans={trial:'Trial 3 hari',monthly:'Bulanan',yearly:'Tahunan',permanent:'Permanen'},statuses={pending:'Belum diaktifkan',scheduled:'Terjadwal',active:'Aktif',expired:'Berakhir',disabled:'Nonaktif'};
let session=null,users=[],phone='',editing=null,credentials=null,screen='login',checking=false;
const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const date=v=>v==null?'—':new Date(v*1000).toLocaleString('id-ID',{dateStyle:'medium',timeStyle:'short'});
function toast(message){$('toast').textContent=message;$('toast').hidden=false;clearTimeout(toast.timer);toast.timer=setTimeout(()=>$('toast').hidden=true,4000)}
async function api(path,body){const response=await fetch(path,{method:body?'POST':'GET',credentials:'same-origin',headers:{...(body?{'Content-Type':'application/json'}:{}),...(session?{'X-CSRF-Token':session.csrf}:{})},...(body?{body:JSON.stringify(body)}:{})});const data=await response.json();if(!response.ok){const e=new Error(data.error||'Permintaan gagal.');e.status=response.status;throw e}return data}
function contact(){document.querySelectorAll('.whatsapp').forEach(a=>{a.hidden=!phone;a.href=phone?'https://wa.me/'+phone+'?text='+encodeURIComponent(session?'Halo HDRG, saya ingin memperpanjang LED Planner. Username: '+session.user.username+'; paket: '+plans[session.user.plan]+'.':'Halo HDRG, saya ingin meminta akun trial / berlangganan LED Planner.'):''});document.querySelectorAll('.contact-fallback').forEach(p=>p.hidden=!!phone)}
function view(next){screen=next;['loginView','adminView','accessWall','planner'].forEach(id=>$(id).hidden=id!==({login:'loginView',admin:'adminView',wall:'accessWall',planner:'planner'}[next]));document.body.classList.toggle('planning',next==='planner');$('account').hidden=!session;if(session){$('identity').textContent=session.user.name+' · '+(session.user.role==='admin'?'Admin':plans[session.user.plan]);$('openAdmin').hidden=session.user.role!=='admin';$('openPlanner').hidden=!session.user.access}contact()}
function wall(title,message){$('wallTitle').textContent=title;$('wallMessage').textContent=message;view('wall')}
function applySession(data,initial=false){session=data;if(!data.user.access){wall(data.user.status==='scheduled'?'Akses belum dimulai':'Masa akses berakhir',data.user.status==='scheduled'?'Akun Anda dapat digunakan mulai '+date(data.user.starts_at)+'.':'Akses '+plans[data.user.plan]+' berakhir pada '+date(data.user.expires_at)+'. Hubungi admin untuk melanjutkan.');return}if(initial||screen==='login'||screen==='wall'){if(data.user.role==='admin')showAdmin();else showPlanner()}}
function showPlanner(){if(!session?.user.access)return;if(!$('planner').getAttribute('src'))$('planner').src='/planner';view('planner')}
async function showAdmin(){if(session?.user.role!=='admin')return;view('admin');await refreshUsers()}
async function refreshUsers(){try{$('adminError').textContent='';users=(await api('/api/admin/users')).users;renderUsers()}catch(e){$('adminError').textContent=e.message;if(e.status===401)await checkSession()}}
function renderUsers(){const query=$('search').value.trim().toLowerCase();const rows=users.filter(u=>(u.name+' '+u.username).toLowerCase().includes(query));$('summary').innerHTML=[['Total pengguna',users.length],['Aktif',users.filter(u=>u.status==='active').length],['Belum mulai',users.filter(u=>['pending','scheduled'].includes(u.status)).length],['Berakhir / nonaktif',users.filter(u=>['expired','disabled'].includes(u.status)).length]].map(([n,v])=>`<div>${n}<strong>${v}</strong></div>`).join('');$('users').innerHTML=rows.map(u=>`<tr><td><b>${esc(u.name)}</b><small>${esc(u.username)}</small></td><td>${plans[u.plan]}</td><td><span class="badge ${u.status}">${statuses[u.status]}</span></td><td>${u.starts_at?date(u.starts_at):'Login pertama'}</td><td>${u.plan==='permanent'?'Tanpa kedaluwarsa':u.expires_at?date(u.expires_at):'Belum mulai'}</td><td><select data-user="${u.id}" aria-label="Kelola ${esc(u.name)}"><option value="">Pilih tindakan</option><option value="license">Ubah paket</option><option value="extend">Perpanjang paket</option><option value="reset_pin">Reset PIN</option><option value="enabled">${u.enabled?'Nonaktifkan':'Aktifkan'} akun</option><option value="reset_session">Reset sesi login</option></select></td></tr>`).join('');$('empty').hidden=!!rows.length;$('empty').textContent=users.length?'Tidak ada pengguna yang cocok.':'Belum ada pengguna. Klik Buat pengguna untuk mulai.'}
function formVisibility(){const f=$('userForm').elements,manual=f.pin_mode.value==='manual';$('manualPinLabel').hidden=!manual;f.pin.required=manual&&!$('pinFields').disabled;const scheduled=f.start_mode.value==='scheduled';$('scheduleLabel').hidden=!scheduled;f.starts_at.required=scheduled&&!$('licenseFields').disabled}
function editDialog(action='create',user=null){editing={action,user};$('userForm').reset();$('formError').textContent='';$('dialogTitle').textContent=action==='create'?'Buat pengguna':action==='reset_pin'?'Reset PIN · '+user.username:'Ubah paket · '+user.username;const profile=action==='create',pin=action!=='license',license=action!=='reset_pin';$('profileFields').hidden=!profile;$('profileFields').querySelectorAll('input').forEach(el=>el.disabled=!profile);$('pinFields').hidden=!pin;$('pinFields').disabled=!pin;$('licenseFields').hidden=!license;$('licenseFields').disabled=!license;if(user)$('userForm').elements.plan.value=user.plan;$('licenseHelp').textContent=action==='license'?'Mengganti paket akan mengganti jadwal lama dan mengeluarkan sesi pengguna. Untuk menambah durasi yang ada, gunakan Perpanjang paket.':'Masa aktif dihitung oleh server. Bulanan dan tahunan mengikuti kalender.';formVisibility();$('userDialog').showModal()}
function showCredentials(result){credentials=result;$('credentialsInfo').innerHTML=`<dt>Pengguna</dt><dd>${esc(result.user.name)}</dd><dt>Username</dt><dd>${esc(result.user.username)}</dd><dt>Paket</dt><dd>${plans[result.user.plan]}</dd><dt>Mulai</dt><dd>${result.user.starts_at?date(result.user.starts_at):'Saat login pertama'}</dd>`;$('resultPin').value=result.pin;$('resultPin').type='password';document.querySelector('[data-toggle="resultPin"]').textContent='Lihat';$('credentialMessage').textContent='';$('credentialsDialog').showModal()}
async function confirmation(title,message){$('confirmTitle').textContent=title;$('confirmMessage').textContent=message;const dialog=$('confirmDialog');dialog.showModal();return new Promise(resolve=>{let done=false;function finish(value){if(done)return;done=true;dialog.close();resolve(value)}$('confirmAction').onclick=()=>finish(true);$('cancelAction').onclick=()=>finish(false);dialog.oncancel=()=>finish(false)})}
$('loginForm').addEventListener('submit',async e=>{e.preventDefault();const button=e.submitter;button.disabled=true;$('loginError').textContent='';try{applySession(await api('/api/login',Object.fromEntries(new FormData(e.target))),true);e.target.reset()}catch(err){$('loginError').textContent=err.message}finally{button.disabled=false}});
$('userForm').addEventListener('submit',async e=>{e.preventDefault();const button=e.submitter;button.disabled=true;const data=Object.fromEntries(new FormData(e.target));if(data.start_mode==='scheduled')data.starts_at=Math.floor(new Date(data.starts_at).getTime()/1000);try{const result=await api(editing.action==='create'?'/api/admin/users':'/api/admin/users/'+editing.user.id,{...data,...(editing.action==='create'?{}:{action:editing.action})});$('userDialog').close();await refreshUsers();if(result.pin)showCredentials(result);else toast('Paket akses diperbarui.')}catch(err){$('formError').textContent=err.message}finally{button.disabled=false}});
$('users').addEventListener('change',async e=>{const select=e.target,action=select.value,user=users.find(u=>u.id===select.dataset.user);if(!user||!action)return;select.value='';if(['license','reset_pin'].includes(action)){editDialog(action,user);return}const messages={enabled:(user.enabled?'Nonaktifkan':'Aktifkan')+' akun '+user.username+'? Sesi login akan direset.',extend:'Tambahkan satu periode '+plans[user.plan]+' untuk '+user.username+'? Sisa masa aktif tetap dipertahankan.',reset_session:'Keluarkan sesi login '+user.username+'? Username dan PIN tetap sama.'};if(!await confirmation('Konfirmasi perubahan',messages[action]))return;try{await api('/api/admin/users/'+user.id,{action,...(action==='enabled'?{enabled:!user.enabled}:{})});await refreshUsers();toast('Perubahan disimpan.')}catch(err){toast(err.message)}});
$('regenerate').onclick=async()=>{if(!credentials)return;const b=$('regenerate');b.disabled=true;try{const r=await api('/api/admin/users/'+credentials.user.id,{action:'reset_pin',pin_mode:'auto'});credentials=r;$('resultPin').value=r.pin;$('credentialMessage').textContent='PIN baru dibuat. PIN sebelumnya tidak berlaku.'}catch(e){$('credentialMessage').textContent=e.message}finally{b.disabled=false}};
$('copyAccess').onclick=async()=>{if(!credentials)return;const u=credentials.user;try{await navigator.clipboard.writeText(`LED Planner\nNama: ${u.name}\nUsername: ${u.username}\nPIN: ${credentials.pin}\nPaket: ${plans[u.plan]}\nMulai: ${u.starts_at?date(u.starts_at):'Saat login pertama'}\nLink: ${location.origin}/`);$('credentialMessage').textContent='Akses disalin. Kirim secara pribadi ke pelanggan.'}catch{$('credentialMessage').textContent='Clipboard tidak tersedia. Gunakan Lihat, lalu salin username dan PIN secara manual.'}};
$('credentialsDialog').addEventListener('close',()=>{credentials=null;$('resultPin').value='';$('credentialsInfo').replaceChildren()});$('userDialog').addEventListener('close',()=>{$('manualPin').value=''});
document.addEventListener('click',e=>{const b=e.target.closest('button');if(!b)return;if(b.dataset.close)$(b.dataset.close).close();if(b.dataset.toggle){const input=$(b.dataset.toggle),show=input.type==='password';input.type=show?'text':'password';b.textContent=show?'Sembunyikan':'Lihat';b.setAttribute('aria-pressed',String(show));b.setAttribute('aria-label',show?'Sembunyikan PIN':'Tampilkan PIN')}});
$('logout').onclick=async()=>{try{await api('/api/logout',{});session=null;$('planner').removeAttribute('src');view('login')}catch(e){toast('Belum berhasil keluar: '+e.message)}};
$('newUser').onclick=()=>editDialog();$('openAdmin').onclick=showAdmin;$('openPlanner').onclick=showPlanner;$('refresh').onclick=refreshUsers;$('search').oninput=renderUsers;$('userForm').elements.pin_mode.onchange=formVisibility;$('userForm').elements.start_mode.onchange=formVisibility;$('retry').onclick=()=>checkSession();
async function checkSession(initial=false){if(checking)return;checking=true;try{applySession(await api('/api/session'),initial)}catch(e){if(e.status===401){session=null;$('planner').removeAttribute('src');document.querySelectorAll('dialog[open]').forEach(d=>d.close());view('login');if(!initial)$('loginError').textContent='Sesi berakhir atau akun berubah. Silakan login kembali.'}else{if(session)session.user.access=false;wall('Koneksi belum tersedia','Tidak dapat memeriksa akses. Periksa koneksi internet lalu coba kembali.')}}finally{checking=false}}
// Fail closed while checking; timestamps and role decisions always come from the server.
setInterval(()=>{if(session)checkSession()},30000);document.addEventListener('visibilitychange',()=>{if(!document.hidden&&session)checkSession()});window.addEventListener('focus',()=>{if(session)checkSession()});
(async()=>{setTimeout(()=>$('splash')?.remove(),1200);try{phone=(await api('/api/config')).whatsapp}catch{}contact();await checkSession(true)})();
